[package]
name = "relay-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
relay-core = { path = "../relay-core" }
dioxus-fullstack = { version = "0.7.10", default-features = false }
serde = { version = "1", features = ["derive"] }
axum = { version = "0.8", optional = true }
dioxus-server = { version = "0.7.10", optional = true }
futures-util = { version = "0.3", optional = true }
http-body = { version = "1", optional = true }
relay-storage = { path = "../relay-storage", optional = true }
humantime = "2.4.0"
bytesize = "2.7.0"

[features]
server = ["relay-core/server", "dioxus-fullstack/server", "dep:axum", "dep:dioxus-server", "dep:futures-util", "dep:http-body", "dep:relay-storage"]
web = ["dioxus-fullstack/web"]
