[package]
name = "relay-targets"
version = "0.1.0"
edition = "2024"

[dependencies]
relay-core = { path = "../relay-core" }
dioxus-fullstack = { version = "0.7.10", default-features = false }
axum = { version = "0.8", optional = true }
dioxus-server = { version = "0.7.10", optional = true }

[features]
server = ["relay-core/server", "dioxus-fullstack/server", "dep:dioxus-server", "dep:axum"]
web = ["dioxus-fullstack/web"]
